from enum import Enum


class Environment(str, Enum):
    TEST = "TEST"
    PRODUCTION = "PRODUCTION"


class MigrationStatus(str, Enum):
    DRAFT = "DRAFT"
    TESTING = "TESTING"
    FAILED = "FAILED"
    SUCCESS = "SUCCESS"
    APPROVED = "APPROVED"
    APPROVAL_INVALID = "APPROVAL_INVALID"
    FINAL_RUNNING = "FINAL_RUNNING"
    COMPLETED = "COMPLETED"


class StatementType(str, Enum):
    ALTER_TABLE = "ALTER_TABLE"
    CREATE_TABLE = "CREATE_TABLE"
    DROP_TABLE = "DROP_TABLE"
    CREATE_INDEX = "CREATE_INDEX"
    DROP_INDEX = "DROP_INDEX"
    CREATE_CONSTRAINT = "CREATE_CONSTRAINT"
    DROP_CONSTRAINT = "DROP_CONSTRAINT"
    CREATE_VIEW = "CREATE_VIEW"
    DROP_VIEW = "DROP_VIEW"
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    OTHER = "OTHER"
