from pathlib import Path
from typing import Protocol, Callable

from app.domains.migration.domain.models import (
    Approval, BackupMetadata, DatabaseConfig, MigrationExecutionResult,
    MigrationStatement
)


ProgressCallback = Callable[[str, int, int], None]


class MigrationParserPort(Protocol):
    def parse_file(self, path: Path) -> list[MigrationStatement]: ...


class DatabasePort(Protocol):
    def test_connection(self, config: DatabaseConfig, password: str) -> None: ...
    def execute(self, config: DatabaseConfig, password: str, sql: str) -> None: ...
    def database_exists(self, config: DatabaseConfig, password: str) -> bool: ...
    def create_database(self, config: DatabaseConfig, password: str) -> None: ...
    def drop_database(self, config: DatabaseConfig, password: str) -> None: ...
    def import_sql(self, config: DatabaseConfig, password: str, sql_file: Path, callback: ProgressCallback | None = None) -> None: ...
    def verify_database(self, config: DatabaseConfig, password: str) -> None: ...


class BackupPort(Protocol):
    def create_backup(
        self,
        config: DatabaseConfig,
        password: str,
        output_file: Path,
        migration_hash: str,
    ) -> BackupMetadata: ...

    def verify_backup(self, metadata: BackupMetadata) -> None: ...


class HistoryPort(Protocol):
    def save_execution(self, result: MigrationExecutionResult, migration_path: Path, backup: BackupMetadata | None = None) -> Path: ...
    def save_approval(self, approval: Approval) -> Path: ...
    def load_approval(self) -> Approval | None: ...
