from pathlib import Path
from typing import Protocol

from app.domains.migration.domain.session import PreMigrationSession


class SessionStorePort(Protocol):
    def clear_all(self) -> None: ...
    def save(self, session: PreMigrationSession) -> None: ...
    def load(self, session_id: str) -> PreMigrationSession: ...
    def file(self, session_id: str, name: str) -> Path: ...
    def write_sql(self, session_id: str, name: str, sql: str) -> Path: ...
